title: processing-opacity
hero_image: images/banner.png
description: processing-opacity description
version: 4
listed: false
copyedit: false
last_tested: "2021-08-03"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
